FROM golang:1.25.0-bookworm

# 作業ディレクトリ
WORKDIR /app

# Air と Goose をインストール
RUN go install github.com/air-verse/air@latest \
    && go install github.com/pressly/goose/v3/cmd/goose@latest

# Go モジュールのコピーと tidy
COPY api/go.mod api/go.sum ./
RUN go mod tidy

# API のソースを /app 配下にコピー
COPY api/. ./

# tmp ディレクトリ作成
RUN mkdir -p tmp

# デバッグ用: コピー内容確認
RUN ls -R /app

# Air 実行
CMD ["air"]
